### ISSUE TITLE
DFD Comments Sept 20

### ISSUE THREAD

**Issue by germonprez** [etrent1988/ISQA3420Assignment1#10]
Hi, 

Here are a few comments on your DFD: 

1) You should have a process between the Manager and the Database. Something like: Query the Database to Retrieve all Software Package and License Information. 

2) Be more explicit in your dataflow naming. For example: 

Database Request --changed to--> Software Package and License Information Request

3) I think that: 

Verify Licenses --should be changed to--> Software Package License Results

**Comment by etrent1988** [comment]
Fixed issues
