### ISSUE TITLE
DFD Comments October 6

### ISSUE THREAD

**Issue by germonprez** [etrent1988/ISQA3420Assignment1#25]
Hi Erik, 

Here are comments: 

1) Going INTO the National Vulnerability Database, Known Vulnerability Request --should be--> Software Package Name. It is the name of the software package that you send to the DB. 

2) Make sure that the Developer and the Software Package Database both get Software Package License and Vulnerability Results -- right now they are only both getting License Results

3) The Developer and Manager should be asking for Software Project License and Vulnerability Results, not just Software Package and License Information (this holds true for the request and results). 

4) The Manager should be able to make a Software Package Policy Documents Request just like the Developer is. This request would run through the Scan the Database for Software Package Policies process. 

Structurally, things are looking good. Just a few things to adjust. 

MG

**Comment by etrent1988** [comment]
![dfd9](https://cloud.githubusercontent.com/assets/21342507/19179479/6c6af4ce-8c23-11e6-8981-ed25ca342254.PNG)

**Comment by etrent1988** [comment]
![dfd9](https://cloud.githubusercontent.com/assets/21342507/19179504/c066ec9a-8c23-11e6-8cc0-5141ad91a9fb.PNG)

**Comment by etrent1988** [comment]
Fixed issues with DFD
