### ISSUE TITLE
DFD Comments #1

### ISSUE THREAD

**Issue by germonprez** [etrent1988/ISQA3420Assignment1#7]
These two processes 

<img width="192" alt="screen shot 2016-09-09 at 12 32 22 pm" src="https://cloud.githubusercontent.com/assets/656208/18396505/983af73e-7689-11e6-9cfd-0cf616f31430.png">

Can just be combined into a single process called something like "Scan Software Package for OSS Components" This process can then send the results to the DB and directly back to the user. 

What you have is two actions by the developer. One is submit a package and the other is request results. Simplify this so that when the developer submits a package, they automatically get the results back from the "Scan Software.." process. This will essentially remove the lower left part of your DFD.

**Comment by etrent1988** [comment]
![dfd2](https://cloud.githubusercontent.com/assets/21342507/18449302/4e617d78-78f4-11e6-8c6c-853b3f25fabd.PNG)

**Comment by etrent1988** [comment]
Combined processes, and simplified the rest of the DFD.
